channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-base==2.3.1
  - jupyterhub-singleuser=2.3.1
  - numpy
  - matplotlib
  - scipy
  - pandas
  - tqdm
  - s3fs
  - awscli
  - scikit-learn
  - datalad
  - datalad-container
  - singularity
  - altair
  - seaborn
  - graphviz
  - pygraphviz
  - python-graphviz
  - jax
  - numba
  - cython
  - torch
  - pytorch
  - torchvision
  - dcm2niix
  - openneuro-py
  - ipyvolume
  - nodejs
  - pymvpa
  - s5cmd
  - imbalanced-learn
  - tensorflow
  - nitime
  - pip:
    - nbgitpuller
    - pymef
    - pybids
    - nipype
    - neuropythy
    - dipy
    - mne
    - nilearn
    - dask[complete]
    - requests==2.28.1
    - nimare==0.0.12
    - osfclient
    - line_profiler
    - memory_profiler
    - black
    - mne_bids
    - ipympl
    - pyfftw
    - pliers
    - duecredit
    - git-credential-helpers
    - cloudpathlib[s3,gz,azure]
    - colorspacious
    - requests
    - platformdirs
